### PR TITLE
reloading project when attrs are changed in data modal

### PR DESCRIPTION
**Pull request by mandeepm91**
Fixes Issue #3

### CODE REVIEW

**Comment by ericberlow** [comment]
@mandeepm91 - I just checked and the problem is still there - I opened the data editing modal (accessed from the 'selection' panel) - dragged the 'keywords' attribute down to change attribute order, closed data modal, opened stats panel, attribute order did not change unless i refresh browser.

**Comment by mandeepm91** [comment]
Ok. I'll take a look. Maybe I need to add the tweak in more places. For now I checked it was working fine for show/hide an attribute

**Comment by ericberlow** [comment]
It seems to be working if you change the attribute rendering type - but not if you re-arrange attribute order.  Also the fix appears to have broken the small button by each attribute in the stats panel which allowed you to hide the attributes from there (in addition to hiding in from the data editing modal). The button used to be a triangle with a menu - now it's a light bulb that says "show attribute"?
 
screen shot 2018-07-18 at 12 14 25 pm

**Comment by mandeepm91** [comment]
@ericberlow I fixed the issue. However it makes the drag and drop a bit slow. I'm seeing how to make it faster. Regarding the light bulb issue, seems like it was due to some other reason because once I deployed the changes, it disappeared. I'll share my update. In the meantime, if you face any other issues, let me know

**Comment by mandeepm91** [comment]
My previous patch wasn't really a good fix. It was slowing down the drag and drop significantly. I have fixed that issue now. Its working fine for me. I have tried show/hide and drag and drop and in both the cases the changes are getting reflected in the stats panel. Let me know if you still face any issues

**Comment by ericberlow** [comment]
looks great @mandeepm91! - i checked and it's working find for me.

**Pull request merged**
